inhibit_all_warnings!

pod 'MJRefresh', ‘~> 3.1.0’
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AVOSCloudIM'
pod 'AVOSCloud'
pod 'JSQMessagesViewController', '7.1.0'
pod 'pop', '~> 1.0.9'
pod 'TSMessages'
pod 'FMDB'